# Generated by Django 2.1.3 on 2018-12-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manage',
            old_name='manage_name',
            new_name='Username',
        ),
    ]
