# Generated by Django 2.1.3 on 2018-12-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_auto_20181205_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manage',
            old_name='Username',
            new_name='username',
        ),
    ]
