# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_auto_20181205_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='标题', max_length=20, unique=True)),
                ('tab', models.CharField(db_column='标签', max_length=30, unique=True)),
                ('comment', models.CharField(db_column='评论', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='创建时间')),
                ('content', models.TextField()),
                ('manager', models.ForeignKey(db_column='上传者', on_delete=django.db.models.deletion.CASCADE, to='backweb.Manage')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='栏目名', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ManyToManyField(db_column='栏目编号', to='backweb.Type'),
        ),
    ]
