# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0004_auto_20181205_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tab',
        ),
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(db_column='简短描述', default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(db_column='是否隐藏', default='0', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(db_column='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(db_column='创建时间'),
        ),
    ]
