# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0006_article_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(db_column='栏目编号', default='1', max_length=5),
        ),
    ]
