# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0007_auto_20181206_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='创建时间'),
        ),
    ]
