# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0009_auto_20181206_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='visibility',
            field=models.CharField(db_column='是否隐藏', default='0', max_length=2),
        ),
    ]
