# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0010_auto_20181206_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(db_column='简短描述', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='标题', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='visibility',
            field=models.CharField(db_column='是否隐藏', default='1', max_length=2),
        ),
    ]
