# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0014_auto_20181207_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(db_column='简短描述', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.Type'),
        ),
    ]
