# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0018_auto_20181207_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Article1',
        ),
    ]
