# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0019_auto_20181207_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='lname',
            field=models.CharField(db_column='别名', max_length=20, null=True),
        ),
    ]
