# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0020_type_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='tdesc',
            field=models.CharField(db_column='描述', max_length=200, null=True),
        ),
    ]
