# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0021_type_tdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='fid',
            field=models.CharField(db_column='父节点', max_length=20, null=True),
        ),
    ]
