# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0022_type_fid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='lname',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='tdesc',
            new_name='desc',
        ),
    ]
